import Head from 'next/head';
import { useEffect } from 'react';
import styled from 'styled-components';
import Aos from 'aos';
import 'aos/dist/aos.css';

import Navbar from './../components/Navbar';
import HomepageHero from './../components/HomepageHero';
import EventInfo from '../components/EventInfo';
import EventSchedule from '../components/EventSchedule';
import BrandBanner from '../components/BrandBanner';
import Footer from '../components/Footer';

export default function Home() {

	useEffect(() => {
		Aos.init();
	}, []);

	return (
		<>
			<Head>
				<title>Metaverse Fashion Week | Decentraland</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<StyledHome>
				<header>
					<Navbar dataAos="fade-down" />
					<HomepageHero dataAos="fade-up" />
				</header>
				<main>
					<EventInfo />
					<EventSchedule />
					<BrandBanner />
				</main>
			</StyledHome>

			<Footer/>
		</>
	)
}

const StyledHome = styled.main`
	header {
		height: 100vh;
		display: flex;
		flex-direction: column;
		min-height: 980px;
	}
`;